module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    USER_DETAIL: 'USER_DETAIL',
    CADASTRO_ADD_NEW: 'CADASTRO_ADD_NEW',
    DEFAULT: ''
  },

  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: 'NOTIFICATION'
  }
});
